### ISSUE TITLE
The delete contextual menu has no effect in the tree for classes

### ISSUE THREAD

**Issue by porchy13** [HEIG-GAPS/slyum#106]
It is not possible to completely delete a class by using the contextual menu "Delete", it as no effect. 

The same contextual menu on relations works.

**Comment by porchy13** [comment]
The contextual menu displayed on a view should have two options : 
- remove from this view
- delete

The contextual menu displayed in the tree should only have a delete option

**Comment by Slyum** [comment]
The main probleme about the delete option (remove from schema) is the undo / redo functionality. When a class is removed from the schema, the undo / redo functionality is reinitialized since the class is removed from all view and the undo / redo functionality cannot undo changes not proper to a view.

**Comment by Slyum** [comment]
fixed
